title: Computational Biology # title which appears for the website
email: Lawrence.Uricchio@tufts.edu #your-email@example.com
description: > # short discription of your website. It is helpful for making your website more discoverable and appears while previewing your website.
    An undergraduate computational biology course at Tufts University.
 
baseurl: "CompBio"   # specify the subpath of your site
url: "https://uricchio.github.io" # the base hostname & protocol for YOUR site, e.g. http://example.com
twitter_username: LawUricchio #
github_username: uricchio #
theme: modernist
plugins:
  - jekyll-feed
